spring:
  application:
    name: zk-sms
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zksms?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    platform: mysql
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      ## 最小空闲连接数量
      minimum-idle: 10
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 20
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 30000
      pool-name: hikariPool
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        min-idle: 1
        max-idle: 8
        max-active: 8
        max-wait: -1ms
    timeout: 1s
  cache:
    redis:
      use-key-prefix: true
      time-to-live: 60s

# JWT 认证配置
jwt:
  #请求头
  tokenHeader: Authorization
  #加密的字符串
  secret: w-eyJleHAiOjE1NDMyMDUyODUsInN1YiI6ImFkbWluIiwiY3JlYXRlZCI6MTU0MDYxMzI4N
  #过期时间，单位：毫秒，这里默认20分钟
  expiration: 1200000
  tokenHead: "Bearer "
