spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zksms?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  redis:
    host: localhost
    port: 6379
    password:
swagger2:
  enable: false
